name: Build and Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: Select Environment
        required: true
        type: choice
        options:
          - Develop
          - Preprod
          - Production
      service:
        description: Name of the service to deploy
        required: true
        type: choice
        options:
          - App
          - Shopify-Web
          - Checkout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-preprod:
    # The type of runner that the job will run on
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        if: (github.event.inputs.deploy_environment == 'Preprod') && (github.ref == 'refs/heads/preprod')
        runs-on: ubuntu-latest

      - name: Run a one-line script
        run: echo Hello, from Preprd!

  deploy-dev:
    # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        if: (github.event.inputs.deploy_environment == 'Develop') && (github.ref == 'refs/heads/develop')
        runs-on: ubuntu-latest

      - name: Run a one-line script
        run: echo Hello, from Develop!
