name: Build and Deploy v2

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: Environment (dev or prod or preprod)
        required: true
        type: string
      app_dir:
        description: name of the service to deploy
        required: true
        type: string