name: Build and Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: Select Environment
        required: true
        type: choice
        options:
          - Develop
          - Preprod
          - Production
      service:
        description: Name of the service to deploy
        required: true
        type: choice
        options:
          - App
          - Shopify-Web
          - Checkout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preprod-deploy:
    if: (github.event.inputs.deploy_environment == 'Preprod') && (github.ref == 'refs/heads/preprod')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #build react scripts
      - name: Build React Scripts
        run: cd theme && npm i --save --legacy-peer-deps && npm run build
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.1.3
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_STAGING_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STAGING_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_STAGING_THEME_ID }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
        with:
          args: --allow-live --ignored-file=config/settings_data.json --ignored-file=locales/*

  develop-deploy:
    if: (github.event.inputs.deploy_environment == 'Develop') && (github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build React Scripts
        run: cd theme && npm i --save --legacy-peer-deps && npm run build
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.1.3
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PRODUCTION_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_PRODUCTION_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_PREPRODUCTION_THEME_ID }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
        with:
          args: --ignored-file=config/settings_data.json --ignored-file=locales/*
