# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: Environment (dev or prod or preprod)
        required: true
        type: string
      app_dir:
        description: name of the service to deploy
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        deploy-prod:
          if: (github.event.inputs.deploy_environment == 'dev') && (github.ref == 'refs/heads/develop')
          name: Run a one-line script
          run: echo Hello, world!
